/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");
const defaultTheme = require("tailwindcss/defaultTheme");
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/Components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    fontFamily: {
      Inter: ["Inter", "sans-serif"],
    },
    colors: {
      ...colors,
      transparent: "transparent",

      // Neutral colors
      "Mneutral-900": "#1a1a1aff",
      "Mneutral-800": "#262626ff",
      "Mneutral-700": "#404040ff",
      "Mneutral-600": "#525252ff",
      "Mneutral-500": "#737373ff",
      "Mneutral-400": "#a3a3a3ff",
      "Mneutral-300": "#d4d4d4ff",
      "Mneutral-200": "#e5e5e5ff",
      "Mneutral-100": "#f5f5f5ff",
      "Mneutral-50": "#fafafaff",

      // Default colors
      "Mdefault-teal": "#30b0c7ff",
      "Mdefault-purple": "#af52deff",
      "Mdefault-indigo": "#5856d6ff",
      "Mdefault-green": "#34c759ff",
      "Mdefault-yellow": "#ffcc00ff",
      "Mdefault-orange": "#ff9500ff",
      "Mdefault-red": "#ff3b30ff",
      "Mdefault-blue": "#007affff",

      // Base colors
      "Mbase-black": "#000000ff",
      "Mbase-white": "#ffffffff",

      // Light mode colors
      "Mbrand-brand-primary-hover": "#0066D6FF",
      "Mbrand-background": "#007AFF14",
      "Mborder-border-brand": "#007AFF1F",
      "Malerts-alerts-success-bg": "#34C75914",
      "Malerts-alerts-success-border": "#34C7591F",
      "Malerts-alerts-warning-bg": "#FFCC0014",
      "Malerts-alerts-warning-border": "#FFCC001F",
      "Malerts-alerts-error-bg": "#FF3B3014",
      "Malerts-error-border": "#FF3B301F",
      "Mbackgrounds-bg-primary": "var(--base-white)",
      "Mbackgrounds-bg-secondary": "var(--neutral-50)",
      "Mbackgrounds-bg-tertiary": "var(--neutral-100)",
      "Mbackgrounds-bg-disable": "var(--neutral-200)",
      "Mbackgrounds-bg-invert": "var(--neutral-900)",
      "Mtext-text-primary": "var(--neutral-900)",
      "Mtext-text-secondary": "var(--neutral-700)",
      "Mtext-text-tertiary": "var(--neutral-500)",
      "Mtext-text-disable": "var(--neutral-400)",
      "Mtext-text-invert": "var(--neutral-50)",
      "Mtext-brand": "var(--default-blue)",
      "Mbrand-brand-primary": "var(--default-blue)",
      "Mborder-border-primary": "var(--neutral-200)",
      "Micon-icon-primary": "var(--neutral-900)",
      "Micon-icon-secondary": "var(--neutral-700)",
      "Micon-icon-tertiary": "var(--neutral-500)",
      "Micon-icon-disable": "var(--neutral-400)",
      "Micon-icon-invert": "var(--neutral-50)",
      "Micon-brand": "var(--default-blue)",
      "Mborder-border-secondary": "var(--neutral-100)",
      "Mborder-border-tertiary": "var(--neutral-50)",
      "Malerts-alerts-success": "var(--default-green)",
      "Malerts-alerts-warning": "var(--default-yellow)",
      "Malerts-alerts-error": "var(--default-red)",
      "Madditional-additional-orange": "var(--default-orange)",
      "Madditional-additional-indigo": "var(--default-indigo)",
      "Madditional-additional-purple": "var(--default-purple)",
      "Madditional-additional-teal": "var(--default-teal)",

      // Dark mode colors
      "Mbackgrounds-bg-primary-dark": "var(--neutral-900)",
      "Mbackgrounds-bg-secondary-dark": "var(--neutral-800)",
      "Mbackgrounds-bg-tertiary-dark": "var(--neutral-700)",
      "Mbackgrounds-bg-disable-dark": "var(--neutral-600)",
      "Mbackgrounds-bg-invert-dark": "var(--neutral-50)",
      "Mtext-text-primary-dark": "var(--neutral-50)",
      "Mtext-text-secondary-dark": "var(--neutral-200)",
      "Mtext-text-tertiary-dark": "var(--neutral-400)",
      "Mtext-text-disable-dark": "var(--neutral-500)",
      "Mtext-text-invert-dark": "var(--neutral-900)",
      "Mborder-border-primary-dark": "var(--neutral-700)",
      "Micon-icon-primary-dark": "var(--neutral-50)",
      "Micon-icon-secondary-dark": "var(--neutral-200)",
      "Micon-icon-tertiary-dark": "var(--neutral-400)",
      "Micon-icon-disable-dark": "var(--neutral-500)",
      "Micon-icon-invert-dark": "var(--neutral-900)",
      "Mborder-border-secondary-dark": "var(--neutral-800)",
      "Mborder-border-tertiary-dark": "var(--neutral-900)",
      "Malerts-alerts-success-dark": "var(--default-green)",
      "Malerts-alerts-warning-dark": "var(--default-yellow)",
      "Malerts-alerts-error-dark": "var(--default-red)",
      "Madditional-additional-orange-dark": "var(--default-orange)",
      "Madditional-additional-indigo-dark": "var(--default-indigo)",
      "Madditional-additional-purple-dark": "var(--default-purple)",
      "Madditional-additional-teal-dark": "var(--default-teal)",
    },
    screens: {
      xxs: "375px",
      xx: "425px",
      ss: "480px",
      xs: "576px",
      ...defaultTheme.screens,
    },
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
